### ISSUE TITLE
Usar coluna de tipo de arma usando a planilha que o Bruno criou

### ISSUE THREAD

**Issue by williamorim** [institutosoudapaz/isdp.armas#23]
A planilha foi compartilhada no Google Drive.

**Comment by blangeani** [comment]
Aba: correcao_tipo  - já incorpora opções para SP E RJ 

https://docs.google.com/spreadsheets/d/1dFupdsYnTW50L1DW7VzxUkEJwTdO6GqIxPoeJiaek2M/edit?gid=75158884#gid=75158884

**Comment by azeloc** [comment]
feito em https://github.com/institutosoudapaz/isdp.armas/blob/master/inst/tabelas_depara/depara_tipo.xlsx
