### ISSUE TITLE
Arrumar tabela de depara

### ISSUE THREAD

**Issue by williamorim** [institutosoudapaz/isdp.armas#29]
Todos os padrões de calibre que estão na tabela do Bruno devem estar na tabela depara de calibre.

O .30 Carbine por exemplo não está.

<img width="423" alt="image" src="https://github.com/user-attachments/assets/65ad6a09-c315-4ec2-8614-34767df0b235">

**Comment by azeloc** [comment]
Agora temos erro só no .32
